### ISSUE TITLE
Python: Don't expose seguid.asserts and seguid.manip

### ISSUE THREAD

**Issue by HenrikBengtsson** [seguid/seguid-python#3]
From https://seguid.readthedocs.io/en/latest/?badge=latest, I see that `seguid.asserts` and `seguid.manip` are "exposed" to the user.  `seguid.asserts` should definitely be an internal API.  I'd argue that `seguid.manip` should be too.  I think we should aim to export as little as possible - we can consider opening it up later, if needed.

**Comment by BjornFJohansson** [comment]
Make internal modules "private", do more imports in __init__.py

**Comment by BjornFJohansson** [comment]
This is fixed in commit 59704f919a7998d265d1ed6d38f254b66cf6bde6 
action fails since yesterday, but tests passes on my computer.

**Comment by HenrikBengtsson** [comment]
> This is fixed in commit [59704f9](https://github.com/seguid/seguid-python/commit/59704f919a7998d265d1ed6d38f254b66cf6bde6) action fails since yesterday, but tests passes on my computer.

Something broken in commit 59704f9. With that commit, I get:

```sh
$ python -m pip install .
Defaulting to user installation because normal site-packages is not writeable
Processing /home/henrik/repositories/seguid/seguid-python
ERROR: Exception:
Traceback (most recent call last):
  File "/home/henrik/.local/lib/python3.10/site-packages/pip/_internal/cli/base_command.py", line 180, in exc_logging_wrapper
    status = run_func(*args)
  File "/home/henrik/.local/lib/python3.10/site-packages/pip/_internal/cli/req_command.py", line 245, in wrapper
    return func(self, options, args)
  File "/home/henrik/.local/lib/python3.10/site-packages/pip/_internal/commands/install.py", line 377, in run
    requirement_set = resolver.resolve(
  File "/home/henrik/.local/lib/python3.10/site-packages/pip/_internal/resolution/resolvelib/resolver.py", line 76, in resolve
    collected = self.factory.collect_root_requirements(root_reqs)
  File "/home/henrik/.local/lib/python3.10/site-packages/pip/_internal/resolution/resolvelib/factory.py", line 534, in collect_root_requirements
    reqs = list(
  File "/home/henrik/.local/lib/python3.10/site-packages/pip/_internal/resolution/resolvelib/factory.py", line 490, in _make_requirements_from_install_req
    cand = self._make_base_candidate_from_link(
  File "/home/henrik/.local/lib/python3.10/site-packages/pip/_internal/resolution/resolvelib/factory.py", line 228, in _make_base_candidate_from_link
    self._link_candidate_cache[link] = LinkCandidate(
  File "/home/henrik/.local/lib/python3.10/site-packages/pip/_internal/resolution/resolvelib/candidates.py", line 290, in __init__
    super().__init__(
  File "/home/henrik/.local/lib/python3.10/site-packages/pip/_internal/resolution/resolvelib/candidates.py", line 156, in __init__
    self.dist = self._prepare()
  File "/home/henrik/.local/lib/python3.10/site-packages/pip/_internal/resolution/resolvelib/candidates.py", line 222, in _prepare
    dist = self._prepare_distribution()
  File "/home/henrik/.local/lib/python3.10/site-packages/pip/_internal/resolution/resolvelib/candidates.py", line 301, in _prepare_distribution
    return preparer.prepare_linked_requirement(self._ireq, parallel_builds=True)
  File "/home/henrik/.local/lib/python3.10/site-packages/pip/_internal/operations/prepare.py", line 525, in prepare_linked_requirement
    return self._prepare_linked_requirement(req, parallel_builds)
  File "/home/henrik/.local/lib/python3.10/site-packages/pip/_internal/operations/prepare.py", line 640, in _prepare_linked_requirement
    dist = _get_prepared_distribution(
  File "/home/henrik/.local/lib/python3.10/site-packages/pip/_internal/operations/prepare.py", line 71, in _get_prepared_distribution
    abstract_dist.prepare_distribution_metadata(
  File "/home/henrik/.local/lib/python3.10/site-packages/pip/_internal/distributions/sdist.py", line 37, in prepare_distribution_metadata
    self.req.load_pyproject_toml()
  File "/home/henrik/.local/lib/python3.10/site-packages/pip/_internal/req/req_install.py", line 516, in load_pyproject_toml
    pyproject_toml_data = load_pyproject_toml(
  File "/home/henrik/.local/lib/python3.10/site-packages/pip/_internal/pyproject.py", line 64, in load_pyproject_toml
    pp_toml = tomli.loads(f.read())
  File "/home/henrik/.local/lib/python3.10/site-packages/pip/_vendor/tomli/_parser.py", line 113, in loads
    pos, header = create_dict_rule(src, pos, out)
  File "/home/henrik/.local/lib/python3.10/site-packages/pip/_vendor/tomli/_parser.py", line 290, in create_dict_rule
    raise suffixed_err(src, pos, f"Cannot declare {key} twice")
pip._vendor.tomli.TOMLDecodeError: Cannot declare ('build-system',) twice (at line 16, column 14)
make: *** [Makefile:13: install] Error 2
...

**Comment by HenrikBengtsson** [comment]
It works if I check out commit 6f402d03 just before that:

```sh
$ git checkout 6f402d035dfe6ddaa47dadb2627fd240b5635f2a
M	seguid-tests
Previous HEAD position was 59704f9 merge __init__.py
HEAD is now at 6f402d0 Merge branch 'main' of github.com:seguid/seguid-python
henrik@hb-x1-2023:~/repositories/seguid/seguid-python$ python -m pip install .
Defaulting to user installation because normal site-packages is not writeable
Processing /home/henrik/repositories/seguid/seguid-python
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Building wheels for collected packages: seguid
  Building wheel for seguid (pyproject.toml) ... done
  Created wheel for seguid: filename=seguid-0.0.3.9007-py3-none-any.whl size=11593 sha256=8255bbf7e642536a8d7f05433de944d65d168b760af04cccc5ed1edddbdb6768
  Stored in directory: /home/henrik/.cache/pip/wheels/02/d1/5e/a33893906e66b7bb87bfd50be98f60b27a9d54e99711018993
Successfully built seguid
DEPRECATION: pdfminer-six -VERSION- has a non-standard version number. pip 24.1 will enforce this behaviour change. A possible replacement is to upgrade to a newer version of pdfminer-six or contact the author to suggest that they release a version with a conforming version number. Discussion can be found at https://github.com/pypa/pip/issues/12063
Installing collected packages: seguid
  Attempting uninstall: seguid
    Found existing installation: seguid 0.0.3.9007
    Uninstalling seguid-0.0.3.9007:
      Successfully uninstalled seguid-0.0.3.9007
Successfully installed seguid-0.0.3.9007
```

**Comment by HenrikBengtsson** [comment]
I suspect that it doesn't like some of your changes to pyproject.toml, cf. https://github.com/seguid/seguid-python/commit/59704f919a7998d265d1ed6d38f254b66cf6bde6#diff-50c86b7ed8ac2cf95bd48334961bf0530cdc77b5a56f852c5c61b89d735fd711L1

**Comment by BjornFJohansson** [comment]
Likely the [poetry-dynamic-versioning](https://github.com/mtkennerly/poetry-dynamic-versioning) "This is a Python 3.7+ plugin for Poetry 1.2.0+ and Poetry Core 1.0.0+ to enable dynamic versioning". I though it nice to set the version via git since we have versions for several languages. Seems not supported by python 3.6. We should go back to setting versions manually.

**Comment by BjornFJohansson** [comment]
Now removed dynamic versioning in  3f2c117c8333110a8273fbea20d0654b5e0cf36d bj branch

**Comment by HenrikBengtsson** [comment]
Merged select parts into the main branch. Looks better now - https://seguid-python.seguid.org/
