### ISSUE TITLE
buggy input validation?

### ISSUE THREAD

**Issue by louisabraham** [seguid/seguid-python#7]
```
>>> ldseguid("AT", "AT", 0)
'ldseguid=AWD-dt5-TEua8RbOWfnctJIu9nA'
>>> ldseguid("AT", "TA", 0)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/opt/homebrew/lib/python3.11/site-packages/seguid/chksum.py", line 248, in ldseguid
    assert_anneal(watson, crick, overhang, table=tb)
  File "/opt/homebrew/lib/python3.11/site-packages/seguid/asserts.py", line 67, in assert_anneal
    raise ValueError("Mismatched basepairs.")
ValueError: Mismatched basepairs.
>>> ldseguid("GATTACA", "CTAATGT", 0)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/opt/homebrew/lib/python3.11/site-packages/seguid/chksum.py", line 248, in ldseguid
    assert_anneal(watson, crick, overhang, table=tb)
  File "/opt/homebrew/lib/python3.11/site-packages/seguid/asserts.py", line 67, in assert_anneal
    raise ValueError("Mismatched basepairs.")
ValueError: Mismatched basepairs.
>>> ldseguid("GATTACA", "TGTAATC", 0)
'ldseguid=XscjVNyZarYrROVgGXUCleJcMC4'
```

I think the input validation is inconsistent. I cannot get if it validates the reverse crick or the normal one.

**Comment by HenrikBengtsson** [comment]
Duplicate of #6

**Comment by louisabraham** [comment]
indeed
